;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  WORKSPACES
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/xworkspaces]
type = internal/xworkspaces
;
;; Only show workspaces defined on the same output as the bar
;;
;; Useful if you want to show monitor specific workspaces
;; on different bars
;;
;; Default: false
;pin-workspaces = true
;
;; Create click handler used to focus desktop
;; Default: true
enable-click = true
;
;; Create scroll handlers used to cycle desktops
;; Default: true
enable-scroll = true
;
;; icon-[0-9]+ = <desktop-name>;<icon>
;; NOTE: The desktop name needs to match the name configured by the WM
;; You can get a list of the defined desktops using:
;; $ xprop -root _NET_DESKTOP_NAMES
icon-0 = 1;1
icon-1 = 2;2
icon-2 = 3;3
icon-3 = 4;4
icon-4 = 5;5
icon-5 = 6;6
icon-6 = 7;7 
icon-7 = 8;8
icon-8 = 9;9
icon-default = 0
;
;
;; Available tags:
;;   <label-monitor>
;;   <label-state> - gets replaced with <label-(active|urgent|occupied|empty)>
;; Default: <label-state>
;format = <label-state>
;format-background = ${colors.background}
;format-foreground = ${colors.foreground}
;
;; Available tokens:
;;   %name%
;; Default: %name%
; Available tokens:
;;   %name%
;;   %icon%
;;   %index%
;; Default: %icon%  %name%
label-active = %icon%
;label-active-background = ${colors.primary}
label-active-foreground = ${colors.primary}
;
;; Available tokens:
;;   %name%
;;   %icon%
;;   %index%
;; Default: %icon%  %name%
label-occupied = %icon%
;label-occupied-background = ${colors.secondary}
label-occupied-foreground = ${colors.secondary}
;
;; Available tokens:
;;   %name%
;;   %icon%
;;   %index%
;; Default: %icon%  %name%
label-urgent = %icon%
label-urgent-background = ${colors.alert}
label-urgent-foreground = #c8cfdc
;
;; Available tokens:
;;   %name%
;;   %icon%
;;   %index%
;; Default: %icon%  %name%
label-empty = %icon%
label-empty-background = ${colors.background}
label-empty-foreground = ${colors.foreground}
;
label-active-padding = 1
label-urgent-padding = 1
label-occupied-padding = 1
label-empty-padding = 1


;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  WINDOW TITLE
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  FILE SYSTEM / DISK SPACE
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/filesystem]
type = internal/fs
interval = 25
mount-0 = / 
format-mounted-prefix = "MNT "
format-mounted-prefix-foreground = "${colors.primary}"
format-mounted = <label-mounted>
label-mounted = %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  PULSEAUDIO / VOLUME
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>
label-volume = %percentage%%
label-muted = muted
label-muted-foreground = ${colors.disabled}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  BLUETOOTH
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/bluetooth]
type = custom/script
exec = /usr/local/bin/bluetooth
interval = 2
;click-left = blueberry
click-right = /usr/local/bin/toggle_bluetooth
format-prefix = ""
format-padding = 1
format-background = #aa0a0a0c
format-foreground = #c8cfdc

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  KEYBOARD
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
;
label-layout = %layout%
label-layout-foreground = ${colors.primary}
;
label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  MEMORY
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  CPU
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%


;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  DEFAULT NETWORK BASE
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  DEFAULT WIFI
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/wifi]
inherit = network-base
interface-type = wireless
label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  DEFAULT ETHERNET
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  SEARCH
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/search]
type = custom/text
content = ""
click-left = "rofi -theme ~/.config/rofi/launcher.rasi -show drun"
content-foreground = ${colors.foreground}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  POWER MENU
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/powermenu]
type = custom/text
content = "⏻ "
click-left = "/usr/local/bin/powermenu"
content-foreground = ${colors.foreground}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  RED SHIFT / BLUE LIGHT
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/redshift]
type = custom/text
content = "RED "
click-left = "redshift"
content-foreground = ${colors.foreground}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  ETHERNET
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/ethernet]
type = custom/script
interval = 2
;inherit = network-base
;interface-type = wired
;format-prefix = "ETH "
;format-prefix-foreground = ${colors.primary}
;click-left = "%local_ip% | xclip -sel clipboard"
;label-connected = %ifname% %local_ip%
;label-foreground = ${colors.primary}
exec = /usr/local/bin/ethernet-status
click-left = /usr/local/bin/copy-ethernet
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label-padding = 1
;label-foreground = ${colors.primary}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  VPN
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/vpn]
type = custom/script
interval = 2
;type = internal/network
;interface = tun0
exec = /usr/local/bin/vpn-status
click-left = /usr/local/bin/copy-vpn
format-prefix = " "
format-prefix-foreground = ${colors.primary} 
label-padding = 1
;label-foreground = ${colors.primary}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  TARGET 
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/target]
type = custom/script
interval = 2
;content = "T "
;content-foreground = ${colors.primary}
exec = /usr/local/bin/hack-target
exec-foreground = ${colors.primary}
click-left = "/usr/local/bin/copy-target"
format = <label>
format-prefix = "什"
format-prefix-foreground = ${colors.primary}
label-padding = 1
;label-foreground = ${colors.primary}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  NETWORK MANAGER
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/nm-launcher]
type = custom/text
format-prefix = "NET 󱘖"
format-prefix-foreground = ${colors.foreground}
content = "NET 󱘖"
content-foreground = ${colors.primary}
click-left = nm-connection-editor

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  DATE
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/date]
type = internal/date
interval = 1
date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S
label = %date%
label-foreground = ${colors.primary}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  BACKLIGHT
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/backlight]
type = internal/xbacklight

; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
card = intel_backlight

; Available tags:
;   <label> (default)
;   <ramp>
;   <bar>
format = <ramp> <label>
format-background = ${color.BACKGROUND}
format-padding = 1

; Available tokens:
;   %percentage% (default)
label = %percentage%%

; Only applies if <ramp> is used

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 
ramp-5 = 
ramp-6 = 
ramp-7 = 
ramp-8 = 
ramp-9 = 
ramp-font = 2
ramp-foreground = ${color.primary}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  BRIGHTNESS
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/brightness]
type = internal/backlight

; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
card = ${system.sys_graphics_card}

enable-scroll = true

; Available tags:
;   <label> (default)
;   <ramp>
;   <bar>
format = <ramp> <label>
format-background = ${colors.background}
format-padding = 1

; Available tokens:
;   %percentage% (default)
label = " %percentage%%"

; Only applies if <ramp> is used

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 
ramp-5 = 
ramp-6 = 
ramp-7 = 
ramp-8 = 
ramp-9 = 
ramp-font = 2
ramp-foreground = ${colors.primary}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  BRIGHTNESS NOT APPLICABLE
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/bna]
type = custom/text

content = "  NA"
content-prefix = ""
content-prefix-font = 1
content-prefix-foreground = ${color.primary}
content-padding = 1

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  BATTERY STATUS
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/battery]
type = internal/battery

; This is useful in case the battery never reports 100% charge
full-at = 99

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = ${system.sys_battery}
adapter = ${system.sys_adapter}

; If an inotify event haven't been reported in this many
; seconds, manually poll for new values.
;
; Needed as a fallback for systems that don't report events
; on sysfs/procfs.
;
; Disable polling by setting the interval to 0.
;
; Default: 5
poll-interval = 2

; see "man date" for details on how to format the time string
; NOTE: if you want to use syntax tags here you need to use %%{...}
; Default: %H:%M:%S
time-format = %H:%M

; Available tags:
;   <label-charging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-charging>
format-charging = <animation-charging> <label-charging>
format-charging-prefix = " "
format-charging-prefix-font = 1
format-charging-prefix-foreground = ${colors.primary}
format-charging-background = ${colors.background}

; Available tags:
;   <label-discharging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-discharging>
format-discharging = <ramp-capacity> <label-discharging>
format-discharging-background = ${colors.background}

; Available tags:
;   <label-full> (default)
;   <bar-capacity>
;   <ramp-capacity>
;format-full = <ramp-capacity> <label-full>

; Available tokens:
;   %percentage% (default)
;   %time%
;   %consumption% (shows current charge rate in watts)

label-charging = " %percentage%%"

; Available tokens:
;   %percentage% (default)
;   %time%
;   %consumption% (shows current discharge rate in watts)
label-discharging = " %percentage%%"

; Available tokens:
;   %percentage% (default)
format-full = <label-full>
format-full-prefix = " "
format-full-prefix-font = 2
format-full-prefix-foreground = ${colors.primary}
format-full-background = ${colors.background}
label-full = %percentage%%

; Only applies if <ramp-capacity> is used
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${colors.primary}
ramp-capacity-font = 2

; Only applies if <animation-charging> is used
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = ${colors.primary}
animation-charging-font = 2
animation-charging-framerate = 700

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  MPD / MUSIC PLAYER
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/mpd]
type = internal/mpd

; Host where mpd is running (either ip or domain name)
; Can also be the full path to a unix socket where mpd is running.
host = 127.0.0.1
port = 6600
;password = myscecretpassword

; Seconds to sleep between progressbar/song timer sync
; Default: 1
interval = 2

; Available tags:
;   <label-song> (default)
;   <label-time>
;   <bar-progress>laced with <icon-(pause|play)>
;   <toggle-stop> - gets replaced with <icon-(stop|play)>
;   <icon-random>
;   <icon-repeat>
;   <icon-repeatone> (deprecated)
;   <icon-single> - Toggle playing only a single song. Replaces <icon-repeatone>
;   <icon-consume>
;   <icon-prev>
;   <icon-stop>
;   <icon-play>
;   <icon-pause>
;   <icon-next>
;   <icon-seekb>
;   <icon-seekf>

format-online = <icon-prev> <toggle> <icon-next> <label-song>
;;format-online-prefix = " "
;;format-online-prefix-font = 2
;;format-online-prefix-foreground = ${colors.GREEN}
format-online-background = ${colors.background}

format-playing = ${self.format-online}
format-paused = ${self.format-online}
format-stopped = ${self.format-online}

; Available tags:
;   <label-offline>
format-offline = <label-offline>
#format-offline-prefix = " "
format-offline-background = ${colors.foreground}

; Available tokens:
;   %artist%
;   %album-artist%
;   %album%
;   %date%
;   %title%
; Default: %artist% - %title%
label-song =  "%artist% - %title%"
label-song-maxlen = 25
label-song-ellipsis = true

; Available tokens:
;   %elapsed%
;   %total%
; Default: %elapsed% / %total%
;;abel-time = %elapsed% / %total%

; Available tokens:
;   None
label-offline = ""

; Only applies if <icon-X> is used
icon-play = " "
icon-play-font = 1
icon-play-foreground = ${colors.foreground}
icon-pause = " "
icon-pause-font = 1
icon-pause-foreground = ${colors.foreground}
icon-stop = 
icon-stop-foreground = ${colors.foreground}
icon-prev = 玲
icon-prev-font = 1
icon-prev-foreground = ${colors.foreground}
icon-next = 怜
icon-next-font = 1
icon-next-foreground = ${colors.foreground}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  SONG STATUS
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/song]
type = internal/mpd

interval = 2

format-online = <label-song>
format-online-font = 5
format-offline = <label-offline>
format-offline-font = 5

format-playing = ${self.format-online}
format-paused = "${self.format-online}"
format-stopped = ""

label-offline =  "Offline"
label-song =  "%title%"
label-song-maxlen = 25
label-song-ellipsis = true

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  ETHERNET CONFIG
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

; If you use both a wired and a wireless network, Add both modules in config.ini
[module/ethernet_config]
type = internal/network
interface = ${system.sys_network_interface}

interval = 1.0
accumulate-stats = true
unknown-as-up = true

format-connected = <label-connected>
format-connected-prefix = "歷 "
format-connected-prefix-foreground = ${colors.primary}
format-connected-prefix-font = 2
format-connected-background = ${colors.background}
format-connected-padding = 1

format-disconnected = <label-disconnected>
format-disconnected-prefix = "轢 "
format-disconnected-prefix-font = 2
format-disconnected-foreground = ${colors.primary}
format-disconnected-background = ${colors.background}
format-disconnected-padding = 1

;label-connected = "%{A1:networkmanager_dmenu &:}%downspeed% | %upspeed%%{A}"
;label-disconnected = "%{A1:networkmanager_dmenu &:}Offline%{A}"

label-connected = "%{A1:networkmanager_dmenu &:} Online"
label-disconnected = "%{A1:networkmanager_dmenu &:} Offline"

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  WIRELESS CONFIG
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/wireless_config]
type = internal/network
interface = ${system.sys_network_interface}

; Seconds to sleep between updates
; Default: 1
interval = 1.0

; Test connectivity every Nth update
; A value of 0 disables the feature
; NOTE: Experimental (needs more testing)
; Default: 0
;ping-interval = 3

; @deprecated: Define min width using token specifiers (%downspeed:min% and %upspeed:min%)
; Minimum output width of upload/download rate
; Default: 3
;;udspeed-minwidth = 5

; Accumulate values from all interfaces
; when querying for up/downspeed rate
; Default: false
accumulate-stats = true

; Consider an `UNKNOWN` interface state as up.
; Some devices have an unknown state, even when they're running
; Default: false
unknown-as-up = true

; Available tags:
;   <label-connected> (default)
;   <ramp-signal>
format-connected = <ramp-signal> <label-connected>
format-connected-background = ${colors.background}
format-connected-padding = 1

; Available tags:
;   <label-disconnected> (default)

format-disconnected = <label-disconnected>
format-disconnected-prefix = "睊 "
format-disconnected-prefix-font = 2
format-disconnected-foreground = ${colors.primary}
format-disconnected-background = ${colors.background}
format-disconnected-padding = 1

; Available tags:
;   <label-connected> (default)
;   <label-packetloss>
;   <animation-packetloss>
;;format-packetloss = <animation-packetloss> <label-connected>

; Available tokens:
;   %ifname%    [wireless+wired]
;   %local_ip%  [wireless+wired]
;   %local_ip6% [wireless+wired]
;   %essid%     [wireless]
;   %signal%    [wireless]
;   %upspeed%   [wireless+wired]
;   %downspeed% [wireless+wired]
;   %linkspeed% [wired]
; Default: %ifname% %local_ip%
;label-connected = "%essid%  %downspeed%"
label-connected = "%{A1:networkmanager_dmenu &:}%essid%%{A}"

; Available tokens:
;   %ifname%    [wireless+wired]
; Default: (none)
label-disconnected = "%{A1:networkmanager_dmenu &:} Offline%{A}"

; Available tokens:
;   %ifname%    [wireless+wired]
;   %local_ip%  [wireless+wired]
;   %local_ip6% [wireless+wired]
;   %essid%     [wireless]
;   %signal%    [wireless]
;   %upspeed%   [wireless+wired]
;   %downspeed% [wireless+wired]
;   %linkspeed% [wired]
; Default: (none)
;label-packetloss = %essid%
;label-packetloss-foreground = #c8cfdc

; Only applies if <ramp-signal> is used
ramp-signal-0 = 直
ramp-signal-1 = 直
ramp-signal-2 = 直
ramp-signal-3 = 直
ramp-signal-4 = 直
ramp-signal-foreground = ${color.primary}
ramp-signal-font = 1

; Only applies if <animation-packetloss> is used
;;animation-packetloss-0 = ⚠
;;animation-packetloss-0-foreground = #c8cfdc
;;animation-packetloss-1 = ⚠
;;animation-packetloss-1-foreground = #c8cfdc
; Framerate in milliseconds
;;animation-packetloss-framerate = 500

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_