;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  MODULES SEPARATOR
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/sep]
type = custom/text
content = "  "
content-background = ${colors.alpha}
content-foreground = ${colors.alpha}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  WORKSPACES
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/xworkspaces]
type = internal/xworkspaces
label-active = %name%
; Used for the currently selected workspaces
; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %nwin% (New in version 3.6.0)
; Default: %icon% %name%
;label-active = %icon% %name%
label-active-foreground = ${colors.primary}
label-active-background = ${colors.background-alt}
;label-active-underline = ${colors.primary}
label-active-padding = 2

; Used for workspaces at least one window
; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %nwin% (New in version 3.6.0)
; Default: %icon% %name%
label-occupied = %name%
;label-occupied-underline = ${colors.primary}
label-occupied-foreground = ${colors.primary}
label-occupied-background = ${colors.background}
label-occupied-padding = 2

; Used for workspaces containing a window that is demanding attention (has the
; urgent bit set)
; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %nwin% (New in version 3.6.0)
; Default: %icon% %name%
label-urgent = %name%
label-urgent-foreground = ${colors.foreground}
label-urgent-background = ${colors.background-alt}
label-urgent-underline = ${colors.primary}
label-urgent-padding = 2

; Used for workspaces without windows
; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %nwin% (New in version 3.6.0)
; Default: %icon% %name%
label-empty = %name%
label-empty-background = ${colors.background}
label-empty-foreground = ${colors.foreground}
label-empty-padding = 2

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  WINDOW TITLE
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%
label-empty-background = ${colors.background}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  DISK SPACE
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/filesystem]
type = internal/fs
interval = 25
mount-0 = "/"
;content = "DATA "
;content-foreground = ${colors.primary}
format-mounted-prefix = " ROOT "
format-mounted-prefix-background = ${colors.background}
format-mounted-prefix-foreground = ${colors.primary}
;format
;format-foreground = ${colors.primary}
;label-name = "DATA "
label-mounted = "%percentage_used%% "  
label-mounted-background = ${colors.background}
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}
label-padding = 1
label-empty-background = ${colors.background}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  PULSEAUDIO / VOLUME
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume-prefix-background = ${colors.background} 
format-volume = <label-volume>
label-volume = %percentage%%
label-volume-background = ${colors.background}
label-muted = muted
label-muted-foreground = ${colors.disabled}
label-muted-background = ${colors.background}
label-padding = 1
label-empty-background = ${colors.background}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  KEYBOARD
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
label-layout = %layout%
label-layout-background = ${colors.background}
label-layout-foreground = ${colors.foreground}
label-indicator-padding = 0
label-indicator-margin = 0
label-indicator-foreground = ${colors.foreground}
label-indicator-background = ${colors.background}
label-padding = 0
label-background = ${colors.background}
label-empty-background = ${colors.background}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  MEMORY
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/memory]
type = internal/memory
interval = 2
format-prefix = " RAM "
format-prefix-background = ${colors.background}
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%
label-background = ${colors.background}
label-padding = 1
label-empty-background = ${colors.background}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;; CPU
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " CPU "
format-prefix-background = ${colors.background}
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%
label-background = ${colors.background}
label-padding = 1
label-empty-background = ${colors.background}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  DEFAULT NETWORK BASE
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %ifname% disconnected
label-foreground = ${colors.primary}
label-empty-background = ${colors.background}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  WIFI
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/wlan]
inherit = network-base
interface-type = wireless
format-prefix = "WIFI "
format-prefix-foreground = ${colors.primary}
label-connected = %ifname% %essid% %local_ip%
label-foreground = ${colors.primary}
label-padding = 1
label-empty-background = ${colors.background}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  ETHERNET
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/eth]
inherit = network-base
interface-type = wired
format-prefix = "ETH "
format-prefix-foreground = ${colors.primary}
label-connected = %ifname% %local_ip%
label-foreground = ${colors.primary}
label-padding = 1
label-empty-background = ${colors.background}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  DATE
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/date]
type = internal/date
interval = 1
date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S
label = %date%
label-background = ${colors.background}
label-foreground = ${colors.primary}
label-padding = 1
label-empty-background = ${colors.background}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  SEARCH
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/search]
type = custom/text
content = "   "
click-left = "rofi -theme ~/.config/rofi/launcher.rasi -show drun"
content-background = ${colors.background}
content-foreground = ${colors.foreground}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  POWERMENU
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/powermenu]
type = custom/text
content = " ⏻  "
click-left = "/usr/local/bin/powermenu"
content-background = ${colors.background}
content-foreground = ${colors.foreground}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  REDSHIFT / BLUE SCREEN
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/redshift]
type = custom/text
content = "RED "
click-left = "redshift"
content-foreground = ${colors.foreground}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  ETHERNET
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/ethernet]
type = custom/script
interval = 2
;inherit = network-base
;interface-type = wired
;format-prefix = "ETH "
;format-prefix-foreground = ${colors.primary}
;click-left = "%local_ip% | xclip -sel clipboard"
;label-connected = %ifname% %local_ip%
;label-foreground = ${colors.primary}
exec = /usr/local/bin/ethernet-status
click-left = /usr/local/bin/copy-ethernet
format-prefix = "  "
format-prefix-background = ${colors.background}
format-prefix-foreground = ${colors.primary}
label-padding = 1
label-background = ${colors.background}
;label-foreground = ${colors.primary}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  VPN
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/vpn]
type = custom/script
interval = 2
;type = internal/network
;interface = tun0
exec = /usr/local/bin/vpn-status
click-left = /usr/local/bin/copy-vpn
format-prefix = "  "
format-prefix-background = ${colors.background}
format-prefix-foreground = ${colors.primary} 
label-padding = 1
label-background = ${colors.background}
;label-foreground = ${colors.primary}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  TARGET
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/target]
type = custom/script
interval = 2
;content = "T "
;content-foreground = ${colors.primary}
exec = /usr/local/bin/hack-target
;exec-foreground = ${colors.primary}
click-left = "/usr/local/bin/copy-target"
;format = <label>
format-prefix = " 什 "
format-prefix-background = ${colors.background}
format-prefix-foreground = ${colors.primary}
label-padding = 1
label-background = ${colors.background}
;label-foreground = ${colors.primary}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  NETWORK MANAGER
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/nm-launcher]
type = custom/text
;format-prefix = "NET 󱘖"
;format-prefix-foreground = ${colors.foreground}
content = "NET 󱘖"
content-foreground = ${colors.primary}
content-background = ${colors.background}
click-left = nm-connection-editor

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  BACKLIGHT
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/backlight]
type = internal/xbacklight

; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
card = intel_backlight

; Available tags:
;   <label> (default)
;   <ramp>
;   <bar>
format = <ramp> <label>
format-background = ${color.BACKGROUND}
format-padding = 1

; Available tokens:
;   %percentage% (default)
label = %percentage%%

; Only applies if <ramp> is used

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 
ramp-5 = 
ramp-6 = 
ramp-7 = 
ramp-8 = 
ramp-9 = 
ramp-font = 2
ramp-foreground = ${color.primary}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  BRIGHTNESS
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/brightness]
type = internal/backlight

; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
card = ${system.sys_graphics_card}

enable-scroll = true

; Available tags:
;   <label> (default)
;   <ramp>
;   <bar>
format = <ramp> <label>
format-background = ${colors.background}
format-padding = 1

; Available tokens:
;   %percentage% (default)
label = "%percentage%%"

; Only applies if <ramp> is used

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 
ramp-5 = 
ramp-6 = 
ramp-7 = 
ramp-8 = 
ramp-9 = 
ramp-font = 1 
ramp-foreground = ${colors.primary}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  BRIGHTNESS NOT APPLICABLE
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/bna]
type = custom/text

content = "  NA"
content-prefix = ""
content-prefix-font = 1
content-prefix-foreground = ${color.primary}
content-padding = 1

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  BATTERY STATUS
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/battery]
type = internal/battery

; This is useful in case the battery never reports 100% charge
full-at = 99

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = ${system.sys_battery}
adapter = ${system.sys_adapter}

; If an inotify event haven't been reported in this many
; seconds, manually poll for new values.
;
; Needed as a fallback for systems that don't report events
; on sysfs/procfs.
;
; Disable polling by setting the interval to 0.
;
; Default: 5
poll-interval = 2

; see "man date" for details on how to format the time string
; NOTE: if you want to use syntax tags here you need to use %%{...}
; Default: %H:%M:%S
time-format = %H:%M

; Available tags:
;   <label-charging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-charging>
format-charging = <animation-charging> <label-charging>
format-charging-prefix = " "
format-charging-prefix-font = 1
format-charging-prefix-foreground = ${colors.primary}
format-charging-background = ${colors.background}

; Available tags:
;   <label-discharging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-discharging>
format-discharging = <ramp-capacity> <label-discharging>
format-discharging-background = ${colors.background}

; Available tags:
;   <label-full> (default)
;   <bar-capacity>
;   <ramp-capacity>
;format-full = <ramp-capacity> <label-full>

; Available tokens:
;   %percentage% (default)
;   %time%
;   %consumption% (shows current charge rate in watts)

label-charging = " %percentage%%"

; Available tokens:
;   %percentage% (default)
;   %time%
;   %consumption% (shows current discharge rate in watts)
label-discharging = " %percentage%%"

; Available tokens:
;   %percentage% (default)
format-full = <label-full>
format-full-prefix =  
format-full-prefix-font = 1
format-full-prefix-foreground = ${colors.primary}
format-full-background = ${colors.background}
label-full = %percentage%%

; Only applies if <ramp-capacity> is used
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${colors.primary}
ramp-capacity-font = 1

; Only applies if <animation-charging> is used
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = ${colors.primary}
animation-charging-font = 1
animation-charging-framerate = 700

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  MPD / MUSIC PLAYER
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/mpd]
type = internal/mpd

; Host where mpd is running (either ip or domain name)
; Can also be the full path to a unix socket where mpd is running.
host = 127.0.0.1
port = 6600
;password = myscecretpassword

; Seconds to sleep between progressbar/song timer sync
; Default: 1
interval = 2

; Available tags:
;   <label-song> (default)
;   <label-time>
;   <bar-progress>laced with <icon-(pause|play)>
;   <toggle-stop> - gets replaced with <icon-(stop|play)>
;   <icon-random>
;   <icon-repeat>
;   <icon-repeatone> (deprecated)
;   <icon-single> - Toggle playing only a single song. Replaces <icon-repeatone>
;   <icon-consume>
;   <icon-prev>
;   <icon-stop>
;   <icon-play>
;   <icon-pause>
;   <icon-next>
;   <icon-seekb>
;   <icon-seekf>

format-online = <icon-prev> <toggle> <icon-next> <label-song>
;;format-online-prefix = " "
;;format-online-prefix-font = 2
;;format-online-prefix-foreground = ${colors.GREEN}
format-online-background = ${colors.background}

format-playing = ${self.format-online}
format-paused = ${self.format-online}
format-stopped = ${self.format-online}

; Available tags:
;   <label-offline>
format-offline = <label-offline>
#format-offline-prefix = " "
format-offline-background = ${colors.background}

; Available tokens:
;   %artist%
;   %album-artist%
;   %album%
;   %date%
;   %title%
; Default: %artist% - %title%
label-song =  "%artist% - %title%"
label-song-maxlen = 15
label-song-ellipsis = true

; Available tokens:
;   %elapsed%
;   %total%
; Default: %elapsed% / %total%
;;abel-time = %elapsed% / %total%

; Available tokens:
;   None
label-offline = ""

; Only applies if <icon-X> is used
icon-play = " "
icon-play-font = 1
icon-play-foreground = ${colors.foreground}
icon-pause = " "
icon-pause-font = 1
icon-pause-foreground = ${colors.foreground}
icon-stop = 
icon-stop-foreground = ${colors.foreground}
icon-prev = 玲
icon-prev-font = 1
icon-prev-foreground = ${colors.foreground}
icon-next = 怜
icon-next-font = 1
icon-next-foreground = ${colors.foregound}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;  SONG STATUS
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/song]
type = internal/mpd

interval = 2

format-online = <label-song>
format-online-font = 5
format-offline = <label-offline>
format-offline-font = 5

format-playing = ${self.format-online}
format-paused = "${self.format-online}"
format-stopped = ""

label-offline =  "Offline"
label-song =  "%title%"
label-song-maxlen = 25
label-song-ellipsis = true
