#!/bin/bash

rotate() {
	degree="$1"
	tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
		case "$(file -b -i "$file")" in
		image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
		*)           mogrify  -rotate "$degree" "$file" ;;
		esac
	done
}

case "$1" in
"C-x")      xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
"C-c")      while read file; do xclip -selection clipboard -target image/png "$file"; done ;;
"C-e")      while read file; do urxvt -bg "#444" -fg "#eee" -sl 0 -title "$file" -e sh -c "exiv2 pr -q -pa '$file' | less" & done ;;
"C-g")      tr '\n' '\0' | xargs -0 gimp & ;;
"C-r")      while read file; do rawtherapee "$file" & done ;;
"C-comma")  rotate 270 ;;
"C-period") rotate  90 ;;
"C-slash")  rotate 180 ;;
esac

set_wallpaper(){
	if [[ ! -z $(ps -efww | grep -vE "grep|launch.sh|scripts" | grep "daku/config.ini" | awk -vpid=$$ '$2 != pid { print $2 }') ]]; then
		POLYBAR="$HOME/.config/polybar/daku/colors.ini"
	fi 

	if [[ ! -z $(ps -efww | grep -vE "grep|launch.sh|scripts" | grep "dakura/config.ini" | awk -vpid=$$ '$2 != pid { print $2 }') ]]; then
		POLYBAR="$HOME/.config/polybar/dakura/colors.ini"
	fi

	if [[ ! -z $(ps -efww | grep -vE "grep|launch.sh|scripts" | grep "shisuru" | awk -vpid=$$ '$2 != pid { print $2 }') ]]; then
		POLYBAR="$HOME/.config/polybar/shisuru/colors.ini"
	fi

	if [[ ! -z $(ps -efww | grep -vE "grep|launch.sh|scripts" | grep "karafuru" | awk -vpid=$$ '$2 != pid { print $2 }') ]]; then
		POLYBAR="$HOME/.config/polybar/karafuru/colors.ini"
	fi

	cat $POLYBAR | grep 'background = #14181d' || cat $POLYBAR | grep 'background = #F2F3F4' || cat $POLYBAR | grep 'background = #FFAFAF'
	if [ $? == 0 ]; then
		killall feh
		feh --bg-fill $1
	else
		killall feh
		/usr/local/bin/pywal $1
		feh --bg-fill "$(< "${HOME}/.cache/wal/wal")"
	fi

	if ! pgrep -f polybar; then
		echo "[i] polybar is not running, launching..."
		VAR=$(grep -F '~/.config/polybar/polybar' ~/.config/bspwm/bspwmrc)
		bash -c "$VAR"
	else
		echo "[+] polybar is already running"
	fi

}

while read file; do
	case "$1" in
	"w") set_wallpaper "$file";;
	esac
done