#!/bin/bash

interface=$(ip link show | grep "tun" | awk '{print $2}' | tr -d ':')
vpn=$(ip a s $interface | grep -Eo 'inet [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | cut -d ' ' -f2)

if [ "$interface" != "" ]; then
	echo "$vpn"
else
	echo "VPN OFF"
fi