#!/usr/bin/bash

# Pentest Tools Directory
sudo mkdir -p /opt/PenTest/{Recon,Vulnerability-Analysis,Exploitation,Web,Post-Exploitaiton/{PrivEsc,Lateral-Movement,Persistence},Wordlists}

# Install Poetry
: '
curl -sSL https://install.python-poetry.org | python3 -
poetry self update
pip install --upgrade pip
sudo apt install -y pipx 
'

# Install NetExec
pipx ensurepath
pipx install git+https://github.com/Pennyw0rth/NetExec

# Install Go
wget https://go.dev/dl/go1.19.5.linux-amd64.tar.gz -O go1.19.5.linux-amd64.tar.gz
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.19.5.linux-amd64.tar.gz
# Install httpx
/usr/local/go/bin/go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
# Install subfinder
/usr/local/go/bin/go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
# Install katana
/usr/local/go/bin/go install github.com/projectdiscovery/katana/cmd/katana@latest
# Install nuclei
/usr/local/go/bin/go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
# Install shodan-cli
pip install shodan

# winPEAS
sudo wget https://github.com/carlospolop/PEASS-ng/releases/download/20230122/winPEASx64.exe -O /opt/PenTest/Post-Exploitaiton/PrivEsc/
sudo wget https://github.com/carlospolop/PEASS-ng/releases/download/20230122/winPEASx86.exe -O /opt/PenTest/Post-Exploitaiton/PrivEsc/

# linPEAS
sudo wget https://github.com/carlospolop/PEASS-ng/releases/download/20230122/linpeas_darwin_amd64 -O /opt/PenTest/Post-Exploitaiton/PrivEsc/
sudo wget https://github.com/carlospolop/PEASS-ng/releases/download/20230122/linpeas_darwin_arm64 -O /opt/PenTest/Post-Exploitaiton/PrivEsc/
sudo wget https://github.com/carlospolop/PEASS-ng/releases/download/20230122/linpeas_linux_386 -O /opt/PenTest/Post-Exploitaiton/PrivEsc/
sudo wget https://github.com/carlospolop/PEASS-ng/releases/download/20230122/linpeas_linux_amd64 -O /opt/PenTest/Post-Exploitaiton/PrivEsc/
sudo wget https://github.com/carlospolop/PEASS-ng/releases/download/20230122/linpeas_linux_arm -O /opt/PenTest/Post-Exploitaiton/PrivEsc/
sudo wget https://github.com/carlospolop/PEASS-ng/releases/download/20230122/linpeas_linux_arm64 -O /opt/PenTest/Post-Exploitaiton/PrivEsc/

# PowerView
sudo wget https://raw.githubusercontent.com/PowerShellMafia/PowerSploit/master/Recon/PowerView.ps1 -O /opt/PenTest/Post-Exploitaiton/PrivEsc/

# SecLists
sudo git clone https://github.com/danielmiessler/SecLists /opt/PenTest/Wordlists/

# Windows Post-Explatation
git clone https://github.com/itm4n/PrintSpoofer /opt/PenTest/Post-Exploitaiton/PrivEsc/
git clone https://github.com/itm4n/FullPowers /opt/PenTest/Post-Exploitaiton/PrivEsc/
git clone https://github.com/itm4n/PrivescCheck /opt/PenTest/Post-Exploitaiton/PrivEsc/
git clone https://github.com/S3cur3Th1sSh1t/WinPwn /opt/PenTest/Post-Exploitaiton/PrivEsc/
