#!/usr/bin/bash

FEH="$HOME/.fehbg"

function default_wallpaper(){
	echo "#!/bin/sh" | tee $FEH ~/.fehbak > /dev/null
	echo "feh --no-fehbg --bg-fill '$1'" | tee -a $FEH ~/.fehbak >> /dev/null
	killall feh 2>/dev/null
	bash ~/.fehbg
	exit
}

function help_menu(){
	echo "Usage: default-wallpaper [-s <wallpaper>] \" ~/Pictures/Wallpapers/wallpaper.png\""
	echo "-s, --set:    Set a default wallpaper."
	echo -e "\nExample: default-wallpaper --set ~/Pictures/Wallpapers/wallpaper.png"
	echo "Information: If want to use \$HOME instead of ~, you have to use double quotes"
	exit
}

if [ -z "$1" ]; then
	help_menu
fi

while [ ! -z "$1" ]; do
  case "$1" in
	--set|-s)
		shift
		default_wallpaper "$1"
		;;
	*)
		help_menu
		;;
  esac
shift
done