#!/usr/bin/bash

if [[ ! -z $(ps -efww | grep -vE "grep|launch.sh|scripts" | grep "daku/config.ini" | awk -vpid=$$ '$2 != pid { print $2 }') ]]; then
	POLYBAR="$HOME/.config/polybar/daku/colors.ini"
fi 

if [[ ! -z $(ps -efww | grep -vE "grep|launch.sh|scripts" | grep "dakura/config.ini" | awk -vpid=$$ '$2 != pid { print $2 }') ]]; then
	POLYBAR="$HOME/.config/polybar/dakura/colors.ini"
fi

if [[ ! -z $(ps -efww | grep -vE "grep|launch.sh|scripts" | grep "shisuru" | awk -vpid=$$ '$2 != pid { print $2 }') ]]; then
	POLYBAR="$HOME/.config/polybar/shisuru/colors.ini"
fi

if [[ ! -z $(ps -efww | grep -vE "grep|launch.sh|scripts" | grep "karafuru" | awk -vpid=$$ '$2 != pid { print $2 }') ]]; then
	POLYBAR="$HOME/.config/polybar/karafuru/colors.ini"
fi

ROFI="$HOME/.config/rofi/colors.rasi"
AWESOME="$HOME/.config/awesome/themes/colorful.lua"
ALACRITTY="$HOME/.config/alacritty/alacritty.yml"

get_colors() {
	wal -i "$1" -q -n
}

apply_colors() {
	# Polybar
	sed -i -e "s/background = #.*/background = $BGT/g" $POLYBAR
	sed -i -e "s/background-alt = #.*/background-alt = $FG/g" $POLYBAR
	sed -i -e "s/foreground = #.*/foreground = $FGA/g" $POLYBAR
	sed -i -e "s/primary = #.*/primary = $COLOR1/g" $POLYBAR
	sed -i -e "s/secondary = #.*/secondary = $COLOR2/g" $POLYBAR
	sed -i -e "s/alert = #.*/alert = $COLOR3/g" $POLYBAR
	sed -i -e "s/disabled = #.*/disabled = $COLOR4/g" $POLYBAR

	# Rofi
	cat > $ROFI <<- EOF
/* COLORS */

* {
	background:    		${BG};
	background-alt:   	${BGT};
	foreground:   		#FFFFFF;
	primary:   			${COLOR1};
	secondary:    		${COLOR2};
	alert:   			${COLOR3};
	disabled: 			${COLOR4};
}
	EOF

	# BSPWM
	bspc config normal_border_color $COLOR1
	bspc config focused_border_color $COLOR2
   	bspc config active_border_color $COLOR3
	bspc config presel_feedback_color $COLOR2

	# Alacritty
	ALA=$(echo $COLOR1 | cut -d "#" -f 2)
	sed -i -e "s/background: '0x*'/background: '0x$ALA'/g" $ALACRITTY
	
	# Polybar restart
	polybar-msg cmd restart
}

if [[ -x "`which wal`" ]]; then
	if [[ "$1" ]]; then
		get_colors "$1"
		
		. "$HOME/.cache/wal/colors.sh"

		BG=`printf "%s\n" "$background"`
		BGT=`echo $BG | sed 's/#/#aa/g'`
		FG=`printf "%s\n" "$color0"`
		FGA=`printf "%s\n" "$color7"`
		COLOR1=`printf "%s\n" "$color1"`
		COLOR2=`printf "%s\n" "$color2"`
		COLOR3=`printf "%s\n" "$color3"`
		COLOR4=`printf "%s\n" "$color4"`
		COLOR5=`printf "%s\n" "$color5"`

		apply_colors
	else
		echo -e "[-] Error: Please enter the absolute path of the wallpaper.\n"
		echo "Usage: ./pywal.sh path/to/image"
	fi
else
	echo "[-] Error: It seems that 'pywal' is not installed."
	exit
fi
